### ISSUE TITLE
generateLocalizedRotues with children

### ISSUE THREAD

**Issue by FabianEllenberger** [wearelucid/vuecid-helpers#5]
it doesn't loop the forEach correctly if you use [nuxt-child](https://nuxtjs.org/api/components-nuxt-child/)

-> https://github.com/wearelucid/vuecid-helpers/blob/master/src/routes/generateLocalizedRoutes.js#L26

**Comment by Jones-S** [comment]
https://github.com/wearelucid/vuecid-helpers/commit/f6adca8f88d0e1f03f6cc4b4ded869ed97ba45e7
